main = ".open-next/worker.js"
name = "myuu-dev"
compatibility_date = "2026-01-02"
compatibility_flags = ["nodejs_compat"]
keep_names = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "myuu.dev"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
